package enumeradores

enum class Turno {
    MANHA, TARDE, NOITE
}

/*6. (GENERALIZADAS) ENUM CLASS
* USEI O ENUM AQUI PARA APRESENTAR OPÇOES LIMITADAS, PORQUE O TURNO SÓ PODE OU SER DE MANHA
* OU DE TARDE OU A NOITE, EVITA VALORES INVALIDOS
* */